name: metropolitan_museum
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  auto_route: ^9.0.0
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.3
  device_info_plus: ^11.3.0
  dio: ^5.8.0+1

  flutter_cache_manager: ^3.4.1
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  path_provider: ^2.1.5
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  

   #Utils
  responsive_sizer: ^3.3.0+1

  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0

  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  objectbox_generator: ^4.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
